[Translation] state_of_css.yml: Options
StateOfJS/locale-pt-BR pull request #32
Opened 2022-03-06 22:56 UTC by thiagoloal

2022-03-06 23:57 UTC, the-physicist commented on state_of_css.yml
> +      t: Eu as vezes escrevo estilos de impressão
```suggestion
      t: Eu às vezes escrevo estilos de impressão
```

2022-03-06 23:57 UTC, the-physicist commented on state_of_css.yml
> +      t: As vezes
```suggestion
      t: Às vezes
```

2022-03-06 23:58 UTC, the-physicist commented on state_of_css.yml
> +      t: As vezes
```suggestion
      t: Às vezes
```

2022-03-07 00:05 UTC, the-physicist commented on state_of_css.yml
> +      t: Aplicativos da Web
```suggestion
      t: Aplicativos Web
```

2022-03-07 00:06 UTC, the-physicist commented on state_of_css.yml
> +      t: Escopo e especificidade
```suggestion
      t: Escopo e Especificidade
```

2022-03-07 00:06 UTC, the-physicist commented on state_of_css.yml
> +      t: Design responsivo
Deve ser título de seções, por isso pode ser interessante manter maíscula

```suggestion
      t: Design Responsivo
```

2022-03-07 00:07 UTC, the-physicist commented on state_of_css.yml
> +      t: Problemas de desempenho
```suggestion
      t: Problemas de Desempenho
```

2022-03-07 00:07 UTC, the-physicist commented on state_of_css.yml
> +      t: Suporte do navegador
```suggestion
      t: Suporte do Navegador
```

2022-03-07 00:07 UTC, the-physicist commented on state_of_css.yml
> +      t: Funções de cor
```suggestion
      t: Funções de Cor
```

2022-03-07 00:08 UTC, the-physicist commented on state_of_css.yml
>        t: Container Queries
```suggestion
      t: Consultas de Contêiner
```

2022-03-07 00:09 UTC, the-physicist commented on state_of_css.yml
> +      t: Aninhando subgrids de nível mais profundo em uma grade pai.
```suggestion
      t: Aninhando subgrids de nível mais profundo em uma grid pai.
```

2022-03-07 00:10 UTC, the-physicist requested changes
Sugestões e padronizações

2022-03-07 00:16 UTC, thiagoloal commented on state_of_css.yml
>        t: Container Queries
nesse caso aqui esse recuso não tem uma tradução para o português conhecida por desenvolvedores :/
Se der uma busca no google vai ver que não é possivel encontrar quando busca assim.
Acho  melhor deixarmos em ingles mesmo

2022-03-07 00:37 UTC, the-physicist commented on state_of_css.yml
>        t: Container Queries
Verdade, é melhor mesmo. Sugeri isso porque antes tínhamos colocado `queries` como `consultas`, mas você tem razão.

2022-03-07 01:07 UTC, merged