[TRANSLATION] Common.yml: General keys
StateOfJS/locale-pt-BR pull request #8
Opened 2022-02-17 02:10 UTC by thiagoloal

2022-02-17 03:33 UTC, the-physicist requested changes
Hello, **Thiago**! Thanks for helping us.

I found some typos and standardization errors, that's why I'm requesting changes.
Allow me to make a few points:

The lines below have a typo or spelling error,

```
12 "Nos"; should be "Nós"
16 "acessao"; should be "acesso"
```
and maybe there's some more.

I recommend using more recurring verb tenses than the most 'correct':

```
14 Avoid duplicate responses
Evitar respostas duplicadas ❌
Evite respostas duplicadas ✔️

16 Give you access to your data
Te dar acesso aos seus dados ❌
Lhe dá acesso aos seus dados ✔️
Te dá acesso aos seus dados ✔️
```

Keep the same formatting as the original to standardize:

```
Review Survey 
Revisar pesquisa ❌
Revisar Pesquisa ✔️
```

Hope these suggestions are relevant! If you need anything else, just call me.

2022-02-17 17:51 UTC, thiagoloal commented on common.yml
> +          Nos pedimos para você criar uma conta para:
```suggestion
          Nós pedimos para você criar uma conta para:
```

2022-02-18 13:30 UTC, thiagoloal commented on common.yml
> +          - Evite respostas duplicadas
```suggestion
          - Evite respostas duplicadas
```
```suggestion
          - Evitar respostas duplicadas
```

2022-02-20 18:56 UTC, the-physicist commented
Well done, Thiago! Let's follow that way then.

2022-02-20 18:57 UTC, merged